language: python
python:
  - "3.6"
services:
  - postgresql
  - redis-server
addons:
  postgresql: 9.6
  apt:
    update: true
    packages:
      - postgresql-9.6-postgis-2.3
    before_script:
      - psql -U postgres -c "create extension postgis"
before_install:
  - sudo apt-get install -y build-essential gdal-bin libgdal-dev libproj-dev libspatialindex-dev
install:
  - pipenv install
  - pipenv install django-anymail[mailgun] django-rest-auth[with_social] django-storages[google]
script:
  - pipenv run ./manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  - DB_NAME=terra
  - DB_HOST=localhost
  - DB_USER=postgres
  - DB_PASSWORD=""
  - RQ_REDIS_URL=redis://localhost:6379/0
  - RQ_TIMEOUT=360
  - SECRET_KEY="foobar"
  - SENTRY_DNS=""
  - WEBCLIENT_URL=http://localhost:3000
